#!/bin/bash

make
for num in {0..3}
do
    for i in {0..10}
    do
        echo "$i"
        ./build/coder/coder data/input/testy4/example${num}.tga "data/fixed/output/ex${num}/test$i.tga" "$i" > "data/fixed/res/ex${num}/res$i.txt"
    done
done